package object

var (
	TM_INDEX    Value = String("__index")
	TM_NEWINDEX Value = String("__newindex")
	TM_GC       Value = String("__gc")
	TM_MODE     Value = String("__mode")
	TM_LEN      Value = String("__len")
	TM_EQ       Value = String("__eq")
	TM_ADD      Value = String("__add")
	TM_SUB      Value = String("__sub")
	TM_MUL      Value = String("__mul")
	TM_MOD      Value = String("__mod")
	TM_POW      Value = String("__pow")
	TM_DIV      Value = String("__div")
	TM_IDIV     Value = String("__idiv")
	TM_BAND     Value = String("__band")
	TM_BOR      Value = String("__bor")
	TM_BXOR     Value = String("__bxor")
	TM_SHL      Value = String("__shl")
	TM_SHR      Value = String("__shr")
	TM_UNM      Value = String("__unm")
	TM_BNOT     Value = String("__bnot")
	TM_LT       Value = String("__lt")
	TM_LE       Value = String("__le")
	TM_CONCAT   Value = String("__concat")
	TM_CALL     Value = String("__call")
)
